---

num_round: 20
num_clients: 2
batch_size: 256
num_partitions: 20
num_classes: 36
num_clients_per_round_fit: 2
num_clients_per_round_eva: 2
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1

#the num_classes represent digits from 0 to 9 in this MNIST dataset context
#Therefore, num_classes would be set to 10 to create a neural network model capable of
#classifying images into one of these 10 classes.